- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove directory
  ansible.builtin.file:
    path: /app
    state: absent


- name: create directory
  ansible.builtin.file:
   path: /app
   state: directory

- name: DOWNLOAD AND EXTRACT APP CONTENT
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes
