- name: install goloang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App pre-requisites
  ansible.builtin.import_tasks:
  file: app_presetup.yml

  args:
    chdir: /app

- name: install golang dependencies
  ansible.builtin.shell: go mod init dispatch;  go get; go build

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
