
- name: Install Mysql Client
  ansible.built.yum:
    name: mysql
    state: installed

- name: load schema
  ansible.builtin.shell: mysql -h mysql-dev.pavani73.store -uroot -pRoboshop@1 </app/schema/{{ component}}.sql


